### ISSUE TITLE
Cetus is not working at all 

### ISSUE THREAD

**Issue by Tamim1357** [Qwokka/Cetus#42]
The newest cetus version, 1.3 isnt working on any websites. (I also tried it on the tank demo game)
Looking into the console while using 1.3, shows  "🐙 CETUS   WebAssembly.instantiateStreaming() intercepted", and not "🐙 CETUS   WebAssembly.instantiate() intercepted"  too
I think because of this, none of the features work - no speedhacking, no searching 

Version 1.0 works fine on the tank game demo but on a wasm io game called https://florr.io/ it does the infinite search issue described in #36
Looking into the console while searching in florr.io, shows cetus.js:51 Uncaught TypeError: Cannot read properties of undefined (reading 'buffer')
    at Cetus.memory (cetus.js:51:44)
    at Cetus.search (cetus.js:146:29)
    at cetus.js:505:34
  Speedhacking works fine in florr.io though
  
I tried to use https://github.com/vakzz/wasm-cheat-engine, in florr.io and it seemed to work fine. (would love cetus also working because of the other features it has)

Anyways, i don't know if this matters but i am using a chromebook on chrome os using chrome browser

**Comment by Qwokka** [comment]
Sounds like another Chromebook issue. Luckily I now own a Chromebook to test on, so I'll see if I can figure out the issue this time. Thanks for the report @Tamim1357 !

**Comment by Tamim1357** [comment]
Ok thanks, hope you can fix the issue with chromebooks, i use cetus for fun alot.
