### ISSUE TITLE
WailParser error, unknown opcode

### ISSUE THREAD

**Issue by lukarson** [Qwokka/Cetus#72]
Hello there,

After intercepting the instantiateStreaming() method, I'm getting the following on [ynoproject.net/2kki](url)

```javascript
Uncaught (in promise) Error: Unknown opcode '253'. Probably parsing incorrectly
    at WailParser._readInstruction (wail.min.js:1:63453)
    at WailParser._readFunction (wail.min.js:1:57142)
    at WailParser._parseCodeSection (wail.min.js:1:52995)
    at WailParser._readSection (wail.min.js:1:31203)
    at WailParser.parse (wail.min.js:1:13823)
    at instrumentBinary (init.js:674:10)
    at handleBuffer (init.js:963:39)
    at init.js:1001:17
```
Few months ago it still worked. I tested on older as well as the latest release. Here it makes the game stuck on loading screen.

**Comment by lukarson** [comment]
Hello Jack,

That's okay, hope you had a great vacation!
Ahh, sorry, indeed I tested with the latest **release**, can confirm the "true latest" git version works fine. 

Thanks a bunch and best of luck with future versions!
