### ISSUE TITLE
ReferenceError: WailParser is not defined

### ISSUE THREAD

**Issue by Pro2stinger** [Qwokka/Cetus#73]
I have a tampermonkey userscript that compiles a wasm file and does something with it and I got this error from cetus.

![Screenshot 2023-12-05 17 27 29](https://github.com/Qwokka/Cetus/assets/93078422/45f57084-9793-4348-b7d2-63d38982a04b)
```
Uncaught (in promise) ReferenceError: WailParser is not defined
    at instrumentBinary (init.js:64:18)
    at WebAssembly.webAssemblyCompileHook [as compile] (init.js:1365:31)
    at compileStreaming (userscript.html?name=!webassembly.js.user.js&id=7953f644-23b7-4311-9710-b59586743504:895:25)
```
full stack trace
```
Uncaught (in promise) ReferenceError: WailParser is not defined
    at instrumentBinary (init.js:64:18)
    at WebAssembly.webAssemblyCompileHook [as compile] (init.js:1365:31)
    at compileStreaming (userscript.html?name=!webassembly.js.user.js&id=7953f644-23b7-4311-9710-b59586743504:895:25)
    instrumentBinary	@	init.js:64
webAssemblyCompileHook	@	init.js:1365
compileStreaming	@	userscript.html?name…10-b59586743504:895
Promise.then (async)		
API	@	userscript.html?name…10-b59586743504:709
Wasm	@	userscript.html?name…10-b59586743504:907
(anonymous)	@	userscript.html?name…10-b59586743504:912
Gt	@	VM5016:9
(anonymous)	@	userscript.html?name…9710-b59586743504:1
window.__f__lpsuuxpn.ti6	@	userscript.html?name…9710-b59586743504:1
Gt	@	VM5016:9
o	@	VM5016:78
(anonymous)	@	VM5016:80
f	@	VM5016:74
St	@	VM5014 content.js:8
m	@	VM5014 content.js:62
u	@	VM5014 content.js:64
(anonymous)	@	VM5014 content.js:64
Sn	@	VM5014 content.js:15
send	@	VM5014 content.js:64
w	@	VM5014 content.js:54
(anonymous)	@	VM5014 content.js:55
(anonymous)	@	VM5014 content.js:27
setTimeout (async)		
(anonymous)	@	VM5014 content.js:27
(anonymous)	@	VM5014 content.js:1
Sn	@	VM5014 content.js:15
e	@	VM5014 content.js:1
oo	@	VM5014 content.js:27
Ko	@	VM5014 content.js:55
(anonymous)	@	VM5014 content.js:54
St	@	VM5014 content.js:8
t	@	VM5014 content.js:9
Go	@	VM5014 content.js:50
ss	@	VM5014 content.js:58
(anonymous)	@	VM5014 content.js:74
(anonymous)	@	VM5014 content.js:15
St	@	VM5014 content.js:8
t	@	VM5014 content.js:9
(anonymous)	@	VM5014 content.js:15
(anonymous)	@	VM5014 content.js:71
```

**Comment by Pro2stinger** [comment]
i just tested it on something else and it has the same error

**Comment by phil-chp** [comment]
<img width="254" alt="Screenshot 2023-12-06 at 8 24 49 PM" src="https://github.com/Qwokka/Cetus/assets/72014356/a5a97cac-25a5-4e9c-a712-f3da0730adf0">
Got the same error from the demo program used in the documentation of Cetus (it's the same in the console)

**Comment by Pro2stinger** [comment]
I managed to fix this by just copying the contents of the `extension` folder into the extension root. It works flawlessly now

**Comment by Qwokka** [comment]
Sorry, I've been away on vacation for a little while. Glad you got this worked out! Feel free to reopen if you have other issues.

Jack
